name: adf-deployment
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: data-factory-deploy
     uses: Azure/data-factory-deploy-action@v1.1.0
     with:
      # Data Factory resource group name
      resourceGroupName: adf-test-clean-njl
      # Data factory name
      dataFactoryName: adf-test-njl
